observers:
  hosts:
    vubuntu:
      ansible_host: 192.168.56.102
      ansible_user: vboxuser
      ansible_connection_type: paramiko

filebeats:
  hosts:
    rocky1:
      ansible_host: 192.168.56.103
    rocky2:
      ansible_host: 192.168.56.105
    rocky3:
      ansible_host: 192.168.56.107
  vars:
    ansible_user: user

nodes:
  children:
    observers:
    filebeats:

all:
  vars:    
    #ansible_connection_type: paramiko
    ansible_connection_type: ssh
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
  # target-2:
  #   ansible_host: 192.168.0.11

targets:
  children:
    target1:
