---
all:
  hosts:
    rocky:
      ansible_host: 192.168.56.103
      ansible_user: user
      ansible_python_interpreter: /usr/bin/python
  children:
    nexus:
      hosts:
        rocky:
  vars:
    #ansible_connection_type: paramiko
    ansible_connection_type: ssh
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
