apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
#  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: 80
