---
  - name: Installing tools
    apt: >
      name={{ item }}
      state=present
      update_cache=yes
    with_items:
      - ntp
      - tcpdump
      - wget
      - openssl
      - curl
      - git
