apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  namespace: default
  labels:
    netology: web
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 8080
