apiVersion: v1
kind: Service
metadata:
  name: netology-svc
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
#      nodePort: 80
#type: NodePort