---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse


- name: Install Vector
  hosts: vector
  roles:
    - vector
  vars: 
    vector_version: "0.50.0"

- name: Install LightHouse
  hosts: vector
  roles:
    - lighthouse
