---
- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Start vector service
      ansible.builtin.service:
        name: vector
        state: restarted
      tags:
        - vector
        - restartservice

  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "/tmp/vector-{{ vector_version }}.rpm"
        mode: '0644'
      tags:
        - vector
        - distr

    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: true

    - name: Install vector
      ansible.builtin.yum:
        name: "/tmp/vector-{{ vector_version }}.rpm"
        state: present
      changed_when: false
      tags:
        - vector
        - distr

    - name: Deploy vector configuration
      ansible.builtin.template:
        src: templates/vector.yaml.j2
        dest: "{{ vector_config_path }}"
        mode: '0644'
      notify: Start vector service
      tags:
        - vector
        - config

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags:
        - vector
        - restart service