---
all:
  hosts:
    nexus-01:
      ansible_host: 84.252.140.252
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    #ansible_connection_type: paramiko
    ansible_connection_type: ssh
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
