#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
- name: user
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
  shell: /bin/bash
  ssh_authorized_keys:
  - "ubuntu:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP8Kjh2WHr1Fv1tdSGmYq3G5or9wrueUjO4VgU1xJeO3 slava@DESKTOP
"
write_files:
  - path: "/var/www/html/index.html"
    permissions: "755"
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Document</title>
      </head>
      <body>
          <h1>Hello world !!!</h1>
          <img src="http://website.yandexcloud.net/sbaucket/img.webp"/>
      </body>
      </html>

    defer: true
