---
- name: Deploy SSH public key
  become: true
  hosts: all
  tasks:
    - name: Add SSH public key to authorized_keys
      ansible.posix.authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '/.ssh/id_ed25519.pub') }}"

    - name: Comment out multiple lines using lineinfile
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^({{ item }})$'  # Matches the exact line
        line: '# \1'            # Prepends a '#' to the line
        backrefs: yes           # Required for using backreferences (item in this case)
      loop:
        - "proxy=http.*"
      when: proxy_host is not defined
