---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: me@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx

#Then, you can create an ingress to expose 'my-service:80' on 'https://my-service.example.com' with:
#microk8s enable ingress
#microk8s kubectl create ingress my-ingress --annotation cert-manager.io/issuer=letsencrypt --rule 'my-service.example.com/*=my-service:80,tls=my-service-tls'
