---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
    prerun: false
    # role-file: requirements.yml
    # requirements-file: requirements.yml

prerun: false

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --force-handlers
        - --inventory=../../inventory/prod.yml
      ansible_navigator:
        - --mode stdout
        - --pull-policy missing
        - --execution-environment-image aragast/netology:latest

  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
    cleanup: cleanup.yml
    prepare: prepare.yml
    side_effect: side_effect.yml
    verify: verify.yml

scenario:
  name: ubuntun
  test_sequence:
    # - dependency
    # - cleanup
    # - destroy
    # - syntax
    # - create
    # - prepare
    - converge
    # - idempotence
    # - side_effect
    # - verify
    # - cleanup
    # - destroy
